language: php
php:
  - '7.1'
before_script:
  # - cp .env.travis .env
  # - composer install --no-interaction

sudo: false

before_install:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer config repositories.oburatongoi vcs https://5e258c4a61bc82deb9c943e09271add4d676df79@github.com/oburatongoi/productivity.git
  # - composer require oburatongoi/productivity dev-master
  - composer require oburatongoi/productivity @dev
  - composer update
  - cp ~/home/travis/build/oburatongoi/productivity/tests/config/.env.travis ./.env
  - rm ~/home/travis/build/config/app.php
  - cp ~/home/travis/build/oburatongoi/productivity/tests/config/app.php ./config
  - php artisan vendor:publish
  - mysql -e 'create database IF NOT EXISTS productivity;' -uroot
  - php artisan migrate
  - cd ./vendor/oburatongoi/productivity
services:
  - mysql
  - redis-server

# script: "phpunit"
script: vendor/bin/phpunit
